spring:
  application:
    name: interview-scheduler

  datasource:
    url: jdbc:mysql://localhost:3306/interview_scheduler
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: arokiajenis@gmail.com
    password: oitr gewh ixeb xksz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080